### PR TITLE
issues/22 : Feature/pg_without_sudo + general cleanup

### PR DESCRIPTION
**Pull request by NorseGaud**
issues/22 | snake66 contribution
added readme for new options
removed psql_simple and using psql instead to clean up code
version bump
notes added

### CODE REVIEW

**Comment by NorseGaud** [comment]
@snake66, take a look at my changes and let me know what you think. I'm going to run tests later this week before anything is merged into master. Wanted your opinion before anything happens though.

**Comment by snake66** [comment]
Looks sane to me. `without_sudo` is better naming, I agree!
All thumbs up!

**Comment by NorseGaud** [comment]
Sorry for the delay. Little overwhelmed. I'll have this tested before the end of the year

**Comment by snake66** [comment]
No stress, let me know if I can help.

**Comment by NorseGaud** [comment]
Looks as if add_extension breaks due to the psql_helpers for psql_on_db. Fixed that. Tested everything and added a few extra bonuses to the release. Going to merge 4.6.0.

**Pull request merged**
